export const en_US = {
  PREVIEW: 'Preview Screensaver',
  REQUEST_SUPPORT: 'Request Support',
  RATE_EXTENSION: 'Rate Extension',
  SOCIAL_MEDIA: 'Social Media',
  FACEBOOK: 'Facebook',
  TWITTER: 'Twitter',
  WEBSITE: 'Website',
  SIMILAR_EXTENSION: 'Similar Extensions',
  SCREENSAVER_IS: 'Screen Saver is',
  ON: 'On',
  OFF: 'Off',
  SLIDE_SHOW_CONTROLS: 'SLIDE SHOW CONTROLS',
  DISPLAY_CONTROLS: 'DISPLAY CONTROLS',
  WAIT_TIME: 'Wait Time',
  HOURS: 'hours',
  MINUTES: 'minutes',
  SECONDS: 'seconds',
  DAYS: 'days',
  SOUND: 'Sound',
  EYES_ANIMATION: 'Eyes Animation',
  RUN_CHROME_BACKGROUND_TITLE: 'Run Chrome in background',
  RUN_CHROME_BACKGROUND_DESC: 'Starts Chrome on computer boot and keeps running when closed',
  SHOW_TIME: 'Show Time',
  HOUR_12: '12 hour',
  HOUR_24: '24 hour',
  LARGE_TIME_LABEL: 'Large time label',
  YOUR_NAME: 'Your name',
  SHOW_DIALOGUES: 'Show dialogues',
  ALL_DISPALYS: 'All displays',
  ALL_DISPLAYS_DESC: 'Show Screensaver on all connected displays',
  CHROME_FULLSCREEN: 'Do not show over fullscreen Chrome windows',
  CHROME_FULLSCREEN_DESC: 'Useful if you are watching videos',
  MEDIA_PLAYING: 'Do not show when a video/audio is playing',
  MEDIA_PLAYING_DESC: 'Useful when you are watching videos',
  BROWSER_MINIMIZED: 'Do not show when browser is minimized',
  BROWSER_MINIMIZED_DESC: 'Useful when you often keep your browser minimized or running in background',
  SCENE_SELECTION: 'Scene Selection',
  SCENE: 'Scene',
  CHOOSE_LANGUAGE: 'Choose Language'
}